export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const ERROR = 'ERROR';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_SHOWS = 'GET_SHOWS';
export const GET_SHOW_DETAILS = 'GET_SHOW_DETAILS';
